---
abstract: unknown
author:
  - 'LNATION <thisusedtobeanemail@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-TableContent
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '1.22'
  HTML::Parser: '3.71'
  Moo: '1.001001'
  perl: '5.006'
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
